version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_eldar
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - etl_network
    shm_size: 128mb

volumes:
  postgres_data:

networks:
  etl_network:
    driver: bridge
